# -*- coding: utf-8 -*-
"""transform-hoasa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l2V5eJrVVadOE0xqO2j4ZD71-hq6fBM9
"""

import pandas as pd

df = pd.read_csv('output/pred-hoasa.csv')

df.head()

f = open('pred.txt', 'w')

f.write('index,ac,air_panas,bau,general,kebersihan,linen,service,sunrise_meal,tv,wifi\n')

for i, row in df.iterrows():
  f.write(str(row[0]))
  f.write(',')
  arr = row[1][1:-1].split(', ')
  for i in range(len(arr)):
    el = arr[i]
    f.write(str(el[1:-1]))
    if (i < len(arr) -1 ):
      f.write(',')
    else:
      f.write('\n')

f.close()

